spring.application.name=jobconnect-be

# 1. Link k?t n?i JDBC
spring.datasource.url=jdbc:postgresql://db.cgugwrxzdqdwnopeceqj.supabase.co:5432/postgres

# 2. Tài kho?n M?t kh?u
spring.datasource.username=postgres
spring.datasource.password=Nhat051004@@

# 3. C?u hình Hibernate (Quan tr?ng ?? t? t?o b?ng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. Driver ?? Java hi?u cách nói chuy?n v?i Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Khai báo c?u hình JWT (B?o m?t)
jwt.secret=ChuoiBiMatCuaHeThongJobConnectSieuCapVipPro123456789
jwt.expiration=86400000

# --- C?U HÌNH CLOUDINARY UPLOAD CV ---
cloudinary.cloud-name=deeehzzs1
cloudinary.api-key=823621431919757
cloudinary.api-secret=dUe9HyMMUYD5GCoIDPHlSMc9QHM


# C?U HÌNH G?I EMAIL (GMAIL SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jobconnect.system@gmail.com
spring.mail.password=auniuakroulirrea 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
