package com.jobconnect.dto.ai;

public enum AiIntent {
    PUBLIC_JOB_SEARCH,
    PUBLIC_STATS,

    CANDIDATE_APPLICATIONS,
    CANDIDATE_PROFILE_REVIEW,
    CANDIDATE_JOB_RECOMMENDATION,

    EMPLOYER_JOB_STATS,
    EMPLOYER_APPLICATION_STATS,

    ADMIN_DASHBOARD_STATS,
    ADMIN_PENDING_APPROVALS,

    GENERAL_HELP
}